import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "لحظه",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <head>
          {/* اضافه کردن لینک به فونت یکان */}
          <link rel="stylesheet" href="https://cdn.fontcdn.ir/font/yekan.css" />
        </head>
      <body>
        {children}
      </body>
    </html>
  );
}
