import type { Metadata } from "next";
import "./globals.css";
import AuthGuard from './components/AuthGuard';
import Script from 'next/script';

export const metadata: Metadata = {
  title: "لحظه",
  description: "Generated by create next app",
  viewport: "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <head>
        <link rel="stylesheet" href="https://cdn.fontcdn.ir/font/yekan.css" />
        <style>{`
          html, body {
            touch-action: pan-x pan-y;
            -webkit-user-select: none;
            user-select: none;
          }
        `}</style>
      </head>
      <body>
        <Script id="disable-zoom" strategy="beforeInteractive">
          {`
            document.addEventListener('touchstart', (event) => {
              if (event.touches.length > 1) {
                event.preventDefault();
              }
            }, { passive: false });
            document.addEventListener('gesturestart', (event) => {
              event.preventDefault();
            });
          `}
        </Script>
        <AuthGuard>{children}</AuthGuard>
      </body>
    </html>
  );
}